### PR TITLE
Fix build issues on linux

### PR DESCRIPTION
**Pull request by aeropl3b**
I am a linux user and had some issues building with gcc/clang on linux.

Note: sandbox segfaults so this is not ready yet.

### CODE REVIEW

**Comment by ChristianPanov** [comment]
Did you manage to fix the sandbox segfault?

**Comment by dolby360** [comment]
> @aeropl3b Did you manage to fix the sandbox segfault?

I'm actually working on this right now.
Seems to be the result of the initialization in format_data.h

**Comment by ChristianPanov** [comment]
@dolby360 Could it possibly be related to this issue #18

**Comment by aeropl3b** [comment]
Okay, so I have gotten this to work in the namespace_headers branch but not here, adding the couple other header fixes that came up after namespacing all of the headers. I think somewhere an include is including the wrong thing and it is just compiling because whatever header was included wrong is not actually needed to compile, or was and just magically worked...this is all very strange.

@ChristianPanov If you don't want to namespace the headers I will put some more effort into figuring this out, otherwise feel free to close this and merge #32 instead

**Pull request merged**
