### PR TITLE
CMake tweaks

### PR DESCRIPTION
**Pull request by friendlyanon**
Adds a development lists file with flags described in https://github.com/ChristianPanov/lwlog/pull/6#issuecomment-751248732

### CODE REVIEW

**Comment by ChristianPanov** [comment]
I found two examples where there aren't hardcoded files.
https://github.com/mmorse1217/cmake-project-template
https://github.com/kigster/cmake-project-template

Take a look at them and tell me if it's applicable to lwlog's case.

And once again, thank you for the contribution and for your time

**Comment by friendlyanon** [comment]
Those are pretty bad templates. The root lists file should strictly be declaring usage and build requirements, the ones in those templates do a lot more, but also use ancient CMake versions.

**Comment by ChristianPanov** [comment]
Got it.
One last thing, can you edit the readme with a CMake installation guide?

**Comment by friendlyanon** [comment]
I don't know if that's advisable, since installation depends on what kind of build system is in use.

Single configruation generator:
```sh
cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
cmake --build build
cmake --install build --prefix prefix
```

Mulit configruation generator:
```sh
cmake -S . -B build
cmake --build build --config Release
cmake --install build --config Release --prefix prefix
```

If you spend a minimal amount of time with CMake you already know these commands. If the library had options that needed some explanation, then maybe it would be nice to include examples, but for a bog-standard project with no options I do not see the point.

**Pull request merged**
