### PR TITLE
Install project and use Ctest

### PR DESCRIPTION
**Pull request by aeropl3b**
This depends on #28

I don't know what I changed exactly here, but the sandbox that builds with this change does not segfault. I had to add another `#include <string_view>` and I removed the `#pragma once` from the top of `sink_impl.hpp` since that should only be included at the end of `sink.h` which is already header-guarded.

This change is large and I can break it into separate PRs. The reason I am presenting it all together is name-spacing the headers becomes more important when the package is installed vs being used directly in another projects source.

The CTest I added as an extra piece. Two new options are available, `LWOG_BUILD_EXAMPLES` and `ENABLE_TESTING`. The latter implies for former for now, but as more tests are added it could make sense to make them separate.

### CODE REVIEW

**Comment by ChristianPanov** [comment]
Good job and thank you for the contribution
If it's not too much hassle, probably breaking down this PR to multiple PRs would be more descriptive in terms of changes
Also, I have a question. Does CMake really take care of optimizations? A contributor mentioned that before.

**Comment by aeropl3b** [comment]
Actually, now that I think about it harder, the lwlog should be lowercase in the config scripts since the project name is lowercase. That is an easy change though of you prefer it to be upper case

**Comment by ChristianPanov** [comment]
Yes it should be lower case, I only changed it because I thought that's a CMake requirement and the casing was messed up

**Comment by aeropl3b** [comment]
Closed because I am making two new ones.

**Comment by aeropl3b** [comment]
> Does CMake really take care of optimizations? A contributor mentioned that before.

Yes, to an extent. CMake will automatically populate flags for (basic linux flags) Release (-O3), RelWithDebInfo (-O2 -g), MinSizeRel (-Os), and Debug (-O0 -g -DNDEBUG).

In addition to these, linking to exported targets, like `Threads::Threads` vs manually passing `-pthreads` as a compile option will add all of the required flags to link and threads threads based on the ThreadsConfig.cmake. That is why in the installation script I am doing this

```cmake
target_include_directories(lwlog
  PUBLIC
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>)
```

Here we are saying that during the build of the project, use the `PROJECT_SOURCE_DIR` as an include, but when the project is installed, expose the `CMAKE_INSTALL_INCLUDEDIR` path as the PUBLIC include interface when linking lwlog.

**Pull request closed without merging**
