### PR TITLE
CMake integration

### LINKED ISSUE #5: CMake support
Hey, any reason why this library doesn't support clients using CMake?

If you just lack the knowledge to properly set a CMake project structure up, then I can make a PR adding that.

### PR DESCRIPTION
**Pull request by friendlyanon**
The project now has a proper structure that can be easily managed by CMake and consumed by CMake clients.

One issue however is that you most likely relied heavily on some non-compliant MSVC extensions due to the missing `/permissive-` flag and the library does not build on GCC. [Edit: builds fine on MSVC tho]  
Note however, this does mean that this flag has any place in the root lists file. The root lists file's only purpose is to define usage and build requirements. If you would like to have tests set up to avoid such issues, then you can take a look at [this project](https://github.com/friendlyanon/ska_sort). I can also provide further help with this if needed.

I have attached a log file with the commands and output of the failure, so you can start investigating it:  
[log.log](https://github.com/ChristianPanov/lwlog/files/5740701/log.log)

Closes #5

### CODE REVIEW

**Comment by ChristianPanov** [comment]
I will be looking into the commits further. I have two questions as of now - I had compiler optimizations turned on, so did you take that into account with the CMake files?
Also another thing - I noticed in the set headers section, you have hardcoded all the header files, and respectively all compilation units are hardcoded as well. That means that adding and removing files would mean to have to edit the CMake lists. Is there a way to automate it, or am I looking at this in a completely wrong way.
Excuse my ignorance on CMake

**Comment by friendlyanon** [comment]
In CMake, you build in release with passing `-D CMAKE_BUILD_TYPE=Release` in configure phase or `--config Release` in build phase, depending on what kind of build system generator you are using.

The sources have to be explicitly listed, so tooling has all the information when generating the build files. In the VS generator's case if you just list `cpp` files then the `Header Files` group won't have anything to be populated with.

Maybe no extensions were used, but I don't see `/permissive-` being used, so it's always a possibility.

**Comment by ChristianPanov** [comment]
Yes, figured as much. 
By the way what about the optimisations. They were speed optimisations, does CMake take that into account?

**Comment by friendlyanon** [comment]
You can define additional flags on top of the library, similar to how `sandbox` does. You can create a `dev/CMakeLists.txt`, include the library with `FetchContent`, then since that makes the library part of your build tree, you can still modify the target `lwlog`.

If you can list the desirable flags, I can push a commit with the above.

**Comment by ChristianPanov** [comment]
Sure thing.
I have speed optimization O2 and enabled intrinsic functions.

**Pull request merged**
